# Generated by Django 2.0.3 on 2019-10-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistlink',
            name='artist',
            field=models.ManyToManyField(blank=True, to='api.Artist'),
        ),
    ]
