# Generated by Django 2.2.4 on 2019-08-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_artist_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
    ]
