# Generated by Django 2.0.3 on 2019-10-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191008_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Physical', 'Physical'), ('Other', 'Other')], max_length=150, null=True, verbose_name='Income Type')),
            ],
        ),
    ]
