# Generated by Django 2.0.3 on 2019-10-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_incomesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('artist', models.ManyToManyField(blank=True, to='api.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('artist', models.ManyToManyField(blank=True, to='api.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product')),
                ('artist', models.ManyToManyField(blank=True, to='api.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='UPC/SKU')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Products', to='api.ProductVariant', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='product',
            name='release',
            field=models.ManyToManyField(blank=True, to='api.Release'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ManyToManyField(blank=True, to='api.Vendor'),
        ),
        migrations.AddField(
            model_name='income',
            name='product',
            field=models.ManyToManyField(blank=True, to='api.Product'),
        ),
        migrations.AddField(
            model_name='income',
            name='release',
            field=models.ManyToManyField(blank=True, to='api.Release'),
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.ManyToManyField(blank=True, to='api.IncomeSource'),
        ),
        migrations.AddField(
            model_name='expense',
            name='product',
            field=models.ManyToManyField(blank=True, to='api.Product'),
        ),
        migrations.AddField(
            model_name='expense',
            name='release',
            field=models.ManyToManyField(blank=True, to='api.Release'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ManyToManyField(blank=True, to='api.Vendor'),
        ),
    ]
