# Generated by Django 2.0.3 on 2019-10-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191019_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='target_markets',
            field=models.TextField(blank=True),
        ),
    ]
