# Generated by Django 2.0.3 on 2019-10-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191019_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='product',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='release',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='income',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='income',
            name='product',
        ),
        migrations.RemoveField(
            model_name='income',
            name='release',
        ),
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
        migrations.RemoveField(
            model_name='product',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='release',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='IncomeSource',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
