# Generated by Django 2.0.3 on 2019-10-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191024_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('release', models.ManyToManyField(blank=True, related_name='tarcks', to='api.Release')),
            ],
        ),
    ]
