# Generated by Django 2.0.3 on 2019-11-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='release',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='api.Release'),
        ),
    ]
