# Generated by Django 2.0.3 on 2019-11-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191101_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(blank=True, null=True, related_name='Tracks', to='api.Artist'),
        ),
    ]
