# Generated by Django 2.0.3 on 2019-12-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_track_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(blank=True, null=True, related_name='tracks', to='api.Artist'),
        ),
    ]
