---
name: tg-info
channels:
  - conda-forge
dependencies:
  - python=3.6
  - psycopg2=2.6.2
  - uwsgi==2.0.15
  - pip=19.2.3=py36_0
  - pip:
      - coreapi==2.3.3
      - django==2.0.3
      - django-cors-headers==3.1.1
      - djangorestframework==3.7.7
      - djangorestframework_simplejwt
      - flake8
      - mysqlclient==1.4.4
      - Pillow==6.2.0
      - yamllint==1.15.0
