# Generated by Django 2.2.4 on 2019-08-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190820_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
        migrations.AddField(
            model_name='artist',
            name='tag',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Artist Tag'),
        ),
    ]
