# Generated by Django 2.2.4 on 2019-08-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_artist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Album Name')),
                ('release_number', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Release Number')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('artist', models.ManyToManyField(to='api.Artist')),
            ],
        ),
    ]
