# Generated by Django 2.2.4 on 2019-09-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_artist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Physical', 'Physical'), ('Other', 'Other')], max_length=150, null=True, verbose_name='Income Type')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='UPC/SKU')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Vendor')),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='current_balance',
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Release Name')),
                ('release_number', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Release Number')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('artist', models.ManyToManyField(to='api.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product')),
                ('artist', models.ManyToManyField(blank=True, to='api.Artist')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Products', to='api.ProductVariant', verbose_name='Variant')),
                ('release', models.ManyToManyField(blank=True, to='api.Release')),
                ('vendor', models.ManyToManyField(blank=True, to='api.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('artist', models.ManyToManyField(blank=True, to='api.Artist')),
                ('product', models.ManyToManyField(blank=True, to='api.Product')),
                ('release', models.ManyToManyField(blank=True, to='api.Release')),
                ('source', models.ManyToManyField(blank=True, to='api.IncomeSource')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('artist', models.ManyToManyField(blank=True, to='api.Artist')),
                ('product', models.ManyToManyField(blank=True, to='api.Product')),
                ('release', models.ManyToManyField(blank=True, to='api.Release')),
                ('vendor', models.ManyToManyField(blank=True, to='api.Vendor')),
            ],
        ),
    ]
