# Generated by Django 2.2.4 on 2019-08-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190821_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesource',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Incomes', to='api.Album', verbose_name='Album'),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Incomes', to='api.Artist', verbose_name='Artist'),
        ),
    ]
