# Generated by Django 2.2.4 on 2019-08-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190820_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='album',
            field=models.ManyToManyField(to='api.Album'),
        ),
        migrations.AddField(
            model_name='income',
            name='artist',
            field=models.ManyToManyField(to='api.Artist'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('album', models.ManyToManyField(to='api.Album')),
                ('artist', models.ManyToManyField(to='api.Artist')),
                ('source', models.ManyToManyField(to='api.Source')),
                ('vendor', models.ManyToManyField(to='api.Vendor')),
            ],
        ),
    ]
