# Generated by Django 2.2.4 on 2019-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190820_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Physical', 'Physical'), ('Other', 'Other')], max_length=150, null=True, verbose_name='Income Type')),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='source',
        ),
        migrations.RemoveField(
            model_name='income',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ManyToManyField(to='api.IncomeSource'),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
