# Generated by Django 2.2.4 on 2019-08-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190821_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomesource',
            name='album',
        ),
        migrations.RemoveField(
            model_name='incomesource',
            name='artist',
        ),
        migrations.AlterField(
            model_name='expense',
            name='album',
            field=models.ManyToManyField(blank=True, to='api.Album'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='artist',
            field=models.ManyToManyField(blank=True, to='api.Artist'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.ManyToManyField(blank=True, to='api.Vendor'),
        ),
        migrations.AlterField(
            model_name='income',
            name='album',
            field=models.ManyToManyField(blank=True, to='api.Album'),
        ),
        migrations.AlterField(
            model_name='income',
            name='artist',
            field=models.ManyToManyField(blank=True, to='api.Artist'),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ManyToManyField(blank=True, to='api.IncomeSource'),
        ),
    ]
