# Generated by Django 2.2.4 on 2019-08-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_artist_known_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='UPC/SKU')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('album', models.ManyToManyField(blank=True, to='api.Album')),
                ('artist', models.ManyToManyField(blank=True, to='api.Artist')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Products', to='api.ProductVariant', verbose_name='Variant')),
                ('vendor', models.ManyToManyField(blank=True, to='api.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='product',
            field=models.ManyToManyField(blank=True, to='api.Product'),
        ),
        migrations.AddField(
            model_name='income',
            name='product',
            field=models.ManyToManyField(blank=True, to='api.Product'),
        ),
    ]
